/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucion9;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdcalcular = new javax.swing.JButton();
        cmdborrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtinicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALQUILER DE TARJETAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, -1));

        cmdcalcular.setText("CALCULAR");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        cmdborrar.setText("BORRAR");
        cmdborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdborrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel2.setText("Monto inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtinicial.setText(" ");
        txtinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicialActionPerformed(evt);
            }
        });
        txtinicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinicialKeyTyped(evt);
            }
        });
        getContentPane().add(txtinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 70, -1));

        jLabel3.setText("Monto final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtfinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfinalKeyTyped(evt);
            }
        });
        getContentPane().add(txtfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, -1));

        jLabel4.setText("Costo de la llamada");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtcosto.setEditable(false);
        txtcosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcostoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed
    double mti,mtf,recargo,total;
    String res;
    
    if(txtinicial.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite monto inicial","Error", JOptionPane.ERROR_MESSAGE);
         txtinicial.requestFocusInWindow();
     }else if(txtfinal.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite monto final","Error", JOptionPane.ERROR_MESSAGE);
         txtfinal.requestFocusInWindow();
     }else{
      
    
    mti=Double.parseDouble(txtinicial.getText());
    mtf=Double.parseDouble(txtfinal.getText());
    
    
    total=mti-mtf;
    
    res=String.valueOf(total);
    txtcosto.setText(res);
     }
    }//GEN-LAST:event_cmdcalcularActionPerformed

    private void txtcostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoKeyTyped

    private void txtinicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinicialKeyTyped
      char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtinicialKeyTyped

    private void txtfinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfinalKeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          }  
    }//GEN-LAST:event_txtfinalKeyTyped

    private void cmdborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdborrarActionPerformed
     txtinicial.setText("");
     txtfinal.setText("");
     txtcosto.setText("");
     
     
     txtinicial.requestFocusInWindow();        
    }//GEN-LAST:event_cmdborrarActionPerformed

    private void txtinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtfinal;
    private javax.swing.JTextField txtinicial;
    // End of variables declaration//GEN-END:variables
}
